name: Compile and Upload Resume PDF
on:
  push:
    branches:
      - main
    paths-ignore:
      - '*.pdf'

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    container:
      image: danteev/texlive:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex

      - name: Post Processing
        run: |
          mkdir build
          cp *.pdf build/
          cp index.html build/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
          clean: true
